# Generated by Django 6.0.5 on 2026-05-12 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=300)),
                ('resumen', models.TextField(blank=True)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='proyectos/documentos/')),
                ('estado', models.CharField(choices=[('inscrito', 'Inscrito'), ('revision', 'Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='inscrito', max_length=50)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('oferta_ea_carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='academico.ofertaeacarrera')),
            ],
            options={
                'db_table': 'proyecto',
            },
        ),
    ]
