# Generated by Django 6.0.3 on 2026-05-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyecto_activo'),
        ('usuarios', '0013_remove_participante_proyecto_remove_tutor_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='proyectos_inscritos', to='usuarios.participante'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tutores',
            field=models.ManyToManyField(blank=True, related_name='proyectos_tutelados', to='usuarios.tutor'),
        ),
    ]
