# Generated by Django 6.0.3 on 2026-06-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_alter_proyecto_estado'),
        ('usuarios', '0014_add_permiso_mis_proyectos'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='tribunales',
            field=models.ManyToManyField(blank=True, related_name='proyectos_evaluar', to='usuarios.tribunal'),
        ),
    ]
