# Generated by Django 6.0.5 on 2026-05-12 04:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'permiso',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id_participante', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_especifico', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('expedicion', models.CharField(choices=[('LP', 'La Paz'), ('CB', 'Cochabamba'), ('SC', 'Santa Cruz'), ('OR', 'Oruro'), ('PT', 'Potosí'), ('CH', 'Chuquisaca'), ('TJ', 'Tarija'), ('BN', 'Beni'), ('PD', 'Pando')], max_length=2)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'participante',
            },
        ),
        migrations.CreateModel(
            name='ParticipanteExt',
            fields=[
                ('id_participante_ext', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=255)),
                ('institucion', models.CharField(max_length=200)),
                ('participante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participante_ext', to='usuarios.participante')),
            ],
            options={
                'db_table': 'participante_ext',
            },
        ),
        migrations.CreateModel(
            name='RolesPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_permisos', to='usuarios.permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_permisos', to='usuarios.rol')),
            ],
            options={
                'db_table': 'roles_permiso',
                'unique_together': {('rol', 'permiso')},
            },
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id_tribunal', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('expedicion', models.CharField(choices=[('LP', 'La Paz'), ('CB', 'Cochabamba'), ('SC', 'Santa Cruz'), ('OR', 'Oruro'), ('PT', 'Potosí'), ('CH', 'Chuquisaca'), ('TJ', 'Tarija'), ('BN', 'Beni'), ('PD', 'Pando')], max_length=2)),
                ('direccion', models.CharField(max_length=255)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tribunal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tribunal',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('cod_empleado', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('expedicion', models.CharField(choices=[('LP', 'La Paz'), ('CB', 'Cochabamba'), ('SC', 'Santa Cruz'), ('OR', 'Oruro'), ('PT', 'Potosí'), ('CH', 'Chuquisaca'), ('TJ', 'Tarija'), ('BN', 'Beni'), ('PD', 'Pando')], max_length=2)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tutor',
            },
        ),
        migrations.CreateModel(
            name='RolesPermisoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles_permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='usuarios.rolespermiso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_permisos_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'roles_permiso_usuario',
                'unique_together': {('usuario', 'roles_permiso')},
            },
        ),
    ]
