# Generated by Django 6.0.5 on 2026-05-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_participante_proyecto_tutor_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tribunal',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
