# Generated by Django 6.0.5 on 2026-05-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_participante_estado_tribunal_estado_tutor_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanteext',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
