# Generated by Django 6.0.5 on 2026-05-14 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_participanteext_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantes', to='usuarios.tutor'),
        ),
    ]
