# Generated by Django 6.0.3 on 2026-05-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_is_2fa_enabled_usuario_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
