# Generated by Django 6.0.5 on 2026-05-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_seed_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribunal',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
