# Generated by Django 6.0.3 on 2026-05-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_tribunal_fcm_token_alter_usuario_totp_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='proyecto',
        ),
    ]
