# Generated by Django 6.0.3 on 2026-06-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_entidadacademica_estado_oferta_estado'),
        ('usuarios', '0014_add_permiso_mis_proyectos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribunal',
            name='areas',
            field=models.ManyToManyField(blank=True, related_name='tribunales', to='academico.area'),
        ),
    ]
