# Generated by Django 6.0.5 on 2026-07-05 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_personal_cargo_fk_firma_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParticipanteExt',
        ),
    ]
