# Generated by Django 6.0.5 on 2026-07-05 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_delete_participanteext'),
    ]

    operations = [
        migrations.CreateModel(
            name='TribunalExt',
            fields=[
                ('id_tribunal_ext', models.AutoField(primary_key=True, serialize=False)),
                ('institucion', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
                ('tribunal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tribunal_ext', to='usuarios.tribunal')),
            ],
            options={
                'db_table': 'tribunal_ext',
            },
        ),
    ]
