# Generated by Django 6.0.5 on 2026-05-12 04:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='Membrete',
            fields=[
                ('id_membrete', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('subtitulo', models.CharField(blank=True, max_length=255)),
                ('logo_unidad', models.ImageField(blank=True, null=True, upload_to='membretes/')),
                ('logo_institucion', models.ImageField(blank=True, null=True, upload_to='membretes/')),
                ('firma', models.ImageField(blank=True, null=True, upload_to='membretes/')),
                ('sello_autoridad', models.ImageField(blank=True, null=True, upload_to='membretes/')),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('pie_pagina1', models.CharField(blank=True, max_length=255)),
                ('pie_pagina2', models.CharField(blank=True, max_length=255)),
                ('pie_pagina3', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'membrete',
            },
        ),
        migrations.CreateModel(
            name='NivelEvento',
            fields=[
                ('id_nivel_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'nivel_evento',
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id_tipo_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tipo_evento',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_actividad', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='eventos.grupo')),
            ],
            options={
                'db_table': 'actividad',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('version', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('gestion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('estado', models.BooleanField(default=True)),
                ('membrete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='eventos.membrete')),
                ('nivel_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='eventos.nivelevento')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='eventos.tipoevento')),
            ],
            options={
                'db_table': 'evento',
                'unique_together': {('nombre', 'version', 'gestion')},
            },
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id_cronograma', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cronogramas', to='eventos.actividad')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cronogramas', to='eventos.evento')),
            ],
            options={
                'db_table': 'cronograma',
                'unique_together': {('evento', 'actividad')},
            },
        ),
    ]
