# Generated by Django 6.0.5 on 2026-05-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelevento',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipoevento',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
