# Generated by Django 6.0.5 on 2026-05-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_nivelevento_estado_tipoevento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='membrete',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
