# Generated by Django 6.0.5 on 2026-05-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_grupo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
