# Generated by Django 6.0.5 on 2026-06-11 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_cronograma_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firmante',
            fields=[
                ('id_firmante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('firma_imagen', models.ImageField(blank=True, null=True, upload_to='firmantes/')),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('estado', models.BooleanField(default=True)),
                ('membrete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmantes', to='eventos.membrete')),
            ],
            options={
                'db_table': 'firmante',
                'ordering': ['orden'],
            },
        ),
    ]
