# Generated by Django 6.0.5 on 2026-05-12 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        ('usuarios', '0002_participante_proyecto_tutor_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanillaEvaluativa',
            fields=[
                ('id_planilla_evaluativa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('nota_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'planilla_evaluativa',
            },
        ),
        migrations.CreateModel(
            name='ActaEvaluacion',
            fields=[
                ('id_acta_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('nota_final', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas_evaluacion', to='proyectos.proyecto')),
                ('planilla_evaluativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas_evaluacion', to='evaluaciones.planillaevaluativa')),
            ],
            options={
                'db_table': 'acta_evaluacion',
                'unique_together': {('proyecto', 'planilla_evaluativa')},
            },
        ),
        migrations.CreateModel(
            name='DetalleEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acta_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_evaluacion', to='evaluaciones.actaevaluacion')),
                ('tribunal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_evaluacion', to='usuarios.tribunal')),
            ],
            options={
                'db_table': 'detalle_evaluacion',
                'unique_together': {('acta_evaluacion', 'tribunal')},
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id_seccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('ponderacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('planilla_evaluativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secciones', to='evaluaciones.planillaevaluativa')),
            ],
            options={
                'db_table': 'seccion',
            },
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id_criterio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criterios', to='evaluaciones.seccion')),
            ],
            options={
                'db_table': 'criterio',
            },
        ),
        migrations.CreateModel(
            name='PuntuacionCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion_criterio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puntuaciones_criterio', to='evaluaciones.criterio')),
                ('detalle_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones_criterio', to='evaluaciones.detalleevaluacion')),
            ],
            options={
                'db_table': 'puntuacion_criterio',
                'unique_together': {('detalle_evaluacion', 'criterio')},
            },
        ),
    ]
