# Generated by Django 6.0.5 on 2026-05-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaevaluacion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='criterio',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='detalleevaluacion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='planillaevaluativa',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='puntuacioncriterio',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seccion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
