# Generated by Django 6.0.3 on 2026-06-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_actaevaluacion_estado_criterio_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevaluacion',
            name='permiso_calificacion_tardia',
            field=models.BooleanField(default=False),
        ),
    ]
