# Generated by Django 6.0.3 on 2026-06-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_detalleevaluacion_permiso_calificacion_tardia'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaevaluacion',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
