# Generated by Django 6.0.5 on 2026-06-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0005_actaevaluacion_consolidada'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaevaluacion',
            name='desempate_prioridad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
