# Generated by Django 6.0.5 on 2026-05-12 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='EntidadAcademica',
            fields=[
                ('id_entidad_academica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'entidad_academica',
            },
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id_modalidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'modalidad',
            },
        ),
        migrations.CreateModel(
            name='CategoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categoria_eventos', to='academico.categoria')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categoria_eventos', to='eventos.evento')),
            ],
            options={
                'db_table': 'categoria_evento',
                'unique_together': {('categoria', 'evento')},
            },
        ),
        migrations.CreateModel(
            name='ModalidadArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modalidad_areas', to='academico.area')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modalidad_areas', to='academico.modalidad')),
            ],
            options={
                'db_table': 'modalidad_area',
                'unique_together': {('modalidad', 'area')},
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id_oferta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas', to='academico.categoriaevento')),
                ('modalidad_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas', to='academico.modalidadarea')),
            ],
            options={
                'db_table': 'oferta',
            },
        ),
        migrations.CreateModel(
            name='OfertaEaCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=200)),
                ('plan', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('entidad_academica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oferta_ea_carreras', to='academico.entidadacademica')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferta_ea_carreras', to='academico.oferta')),
            ],
            options={
                'db_table': 'oferta_ea_carrera',
                'unique_together': {('oferta', 'entidad_academica', 'carrera')},
            },
        ),
    ]
