# Generated by Django 6.0.5 on 2026-05-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidadacademica',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
