# Generated by Django 6.0.5 on 2026-06-30 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_refactor_ofertaeacarrera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='nombre',
        ),
    ]
