# Generated by Django 6.0.5 on 2026-05-12 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('evaluaciones', '0001_initial'),
        ('eventos', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id_descriptor', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'descriptor',
            },
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id_plantilla', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
            ],
            options={
                'db_table': 'plantilla',
            },
        ),
        migrations.CreateModel(
            name='TipoDescriptor',
            fields=[
                ('id_tipo_descriptor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tipo_descriptor',
            },
        ),
        migrations.CreateModel(
            name='CandidatoPremio',
            fields=[
                ('id_candidato_premio', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observacion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('candidato', 'Candidato'), ('ganador', 'Ganador'), ('descartado', 'Descartado')], default='candidato', max_length=20)),
                ('acta_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatos_premio', to='evaluaciones.actaevaluacion')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatos_premio', to='proyectos.proyecto')),
            ],
            options={
                'db_table': 'candidato_premio',
            },
        ),
        migrations.CreateModel(
            name='GanadorPremio',
            fields=[
                ('id_ganador_premio', models.AutoField(primary_key=True, serialize=False)),
                ('candidato_premio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ganador', to='premiacion.candidatopremio')),
            ],
            options={
                'db_table': 'ganador_premio',
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id_certificado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('ganador_premio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificados', to='premiacion.ganadorpremio')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificados', to='premiacion.plantilla')),
            ],
            options={
                'db_table': 'certificado',
            },
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id_premio', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('numero_ganadores', models.PositiveSmallIntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='premios', to='academico.area')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='premios', to='eventos.evento')),
            ],
            options={
                'db_table': 'premio',
            },
        ),
        migrations.AddField(
            model_name='candidatopremio',
            name='premio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatos', to='premiacion.premio'),
        ),
        migrations.CreateModel(
            name='PremioDescriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='premio_descriptores', to='premiacion.descriptor')),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premio_descriptores', to='premiacion.premio')),
            ],
            options={
                'db_table': 'premio_descriptor',
                'unique_together': {('premio', 'descriptor')},
            },
        ),
        migrations.AddField(
            model_name='premio',
            name='descriptores',
            field=models.ManyToManyField(related_name='premios', through='premiacion.PremioDescriptor', to='premiacion.descriptor'),
        ),
        migrations.AddField(
            model_name='descriptor',
            name='tipo_descriptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descriptores', to='premiacion.tipodescriptor'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatopremio',
            unique_together={('premio', 'proyecto')},
        ),
    ]
