# Generated by Django 6.0.5 on 2026-05-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatopremio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='descriptor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ganadorpremio',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipodescriptor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
