# Generated by Django 6.0.3 on 2026-05-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiacion', '0002_candidatopremio_activo_certificado_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premio',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
