# Generated by Django 6.0.5 on 2026-06-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiacion', '0003_make_monto_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='orientacion',
            field=models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='horizontal', max_length=20),
        ),
    ]
