# Generated by Django 6.0.5 on 2026-06-12 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiacion', '0004_plantilla_orientacion'),
        ('usuarios', '0015_tribunal_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionPremio',
            fields=[
                ('id_asignacion_premio', models.AutoField(primary_key=True, serialize=False)),
                ('monto_asignado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observacion', models.TextField(blank=True)),
                ('impresa', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ganador_premio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='premiacion.ganadorpremio')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_premio', to='usuarios.participante')),
            ],
            options={
                'db_table': 'asignacion_premio',
                'unique_together': {('ganador_premio', 'participante')},
            },
        ),
    ]
