# Generated by Django 6.0.5 on 2026-06-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiacion', '0005_asignacionpremio'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionpremio',
            name='estado_pago',
            field=models.CharField(choices=[('sin_configurar', 'Sin Configurar'), ('configurado', 'Configurado'), ('pagado', 'Pagado')], default='sin_configurar', max_length=20),
        ),
        migrations.AddField(
            model_name='asignacionpremio',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacionpremio',
            name='metodo_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('qr', 'QR'), ('efectivo', 'Efectivo')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='asignacionpremio',
            name='qr_imagen',
            field=models.TextField(blank=True, default=''),
        ),
    ]
