# Generated by Django 6.0.5 on 2026-06-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiacion', '0006_asignacionpremio_estado_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionpremio',
            name='comprobante_pago_imagen',
            field=models.TextField(blank=True, default=''),
        ),
    ]
